SortFilterPageDemo/SortFilterPageDemo/Models/Aluno.cs
namespace SortFilterPageDemo.Models
{
    public class Aluno
    {
        public int ID { get; set; }
        public string Nome { get; set; }
    }
}

SortFilterPageDemo/SortFilterPageDemo/Models/ErrorViewModel.cs
using System;

namespace SortFilterPageDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SortFilterPageDemo/SortFilterPageDemo/Controllers/AlunosController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SortFilterPageDemo.Configuration;
using SortFilterPageDemo.Data;
using SortFilterPageDemo.Models;
using System.Threading.Tasks;
using System.Linq;
using ReflectionIT.Mvc.Paging;

namespace SortFilterPageDemo.Controllers
{
    public class AlunosController : Controller
    {
        private readonly MeuDbContext _context;

        public AlunosController(MeuDbContext dbContext)
        {
            _context = dbContext;
        }

        public async Task<IActionResult> Index(string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber)
        {
            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            var students = from s in _context.Alunos
                           select s;

            if (!string.IsNullOrEmpty(searchString))
            {
                students = students.Where(s => s.Nome.Contains(searchString));
            }


            int pageSize = 3;

            return View(await PaginatedList<Aluno>.CreateAsync(students.AsNoTracking(), pageNumber ?? 1, pageSize));

        }

    }
}

SortFilterPageDemo/SortFilterPageDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SortFilterPageDemo.Models;

namespace SortFilterPageDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SortFilterPageDemo/SortFilterPageDemo/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReflectionIT.Mvc.Paging;
using SortFilterPageDemo.Data;
using SortFilterPageDemo.Models;

namespace SortFilterPageDemo.Controllers
{
    public class StudentsController : Controller
    {
        private readonly MeuDbContext _context;

        public StudentsController(MeuDbContext dbContext)
        {
            _context = dbContext;
        }


        public IActionResult Index(int page = 1)
        {
            IEnumerable<Aluno> qry = _context.Alunos.AsNoTracking();
            var model = PagingList.Create(qry, 10, page);

            return View(model);
        }
    }
}

SortFilterPageDemo/SortFilterPageDemo/Views/Alunos/Index.cshtml
@using SortFilterPageDemo.Configuration
@model PaginatedList<SortFilterPageDemo.Models.Aluno>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                Nome
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

Page @(Model.TotalPages < Model.PageIndex ? 0 : Model.PageIndex) of @Model.TotalPages
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>

SortFilterPageDemo/SortFilterPageDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SortFilterPageDemo/SortFilterPageDemo/Views/Shared/Components/Pager/SmallPager.cshtml
@model ReflectionIT.Mvc.Paging.IPagingList

@{
    var start = this.Model.StartPageIndex;
    var stop = this.Model.StopPageIndex;
}

@if (this.Model.PageCount > 1)
{
    <ul class="pagination pagination-sm">

        @if (start > 1)
        {
            <li>
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(1))" aria-label="First">
                    <span aria-hidden="true">1</span>
                </a>
            </li>
        }

        @if (this.Model.PageIndex > 1)
        {
            <li>
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageIndex - 1))" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        }

        @for (int i = start; i <= stop; i++)
        {
            <li class="@((Model.PageIndex == i) ? "active" : null)">
                @Html.ActionLink(i.ToString(), Model.Action, Model.GetRouteValueForPage(i))
            </li>
        }

        @if (this.Model.PageIndex < this.Model.PageCount)
        {
            <li>
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageIndex + 1))" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        }

        @if (stop < this.Model.PageCount)
        {
            <li>
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageCount))" aria-label="Last">
                    <span aria-hidden="true">@this.Model.PageCount</span>
                </a>
            </li>
        }

    </ul>
}

SortFilterPageDemo/SortFilterPageDemo/Views/Shared/SmallPager.cshtml
@model ReflectionIT.Mvc.Paging.IPagingList

@{
    var start = this.Model.StartPageIndex;
    var stop = this.Model.StopPageIndex;
}

@if (this.Model.PageCount > 1)
{
    <ul class="pagination pagination-sm">

        @if (start > 1)
        {
            <li>
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(1))" aria-label="First">
                    <span aria-hidden="true">1</span>
                </a>
            </li>
        }

        @if (this.Model.PageIndex > 1)
        {
            <li>
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageIndex - 1))" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        }

        @for (int i = start; i <= stop; i++)
        {
            <li class="@((Model.PageIndex == i) ? "active" : null)">
                @Html.ActionLink(i.ToString(), Model.Action, Model.GetRouteValueForPage(i))
            </li>
        }

        @if (this.Model.PageIndex < this.Model.PageCount)
        {
            <li>
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageIndex + 1))" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        }

        @if (stop < this.Model.PageCount)
        {
            <li>
                <a href="@Url.Action(Model.Action, Model.GetRouteValueForPage(this.Model.PageCount))" aria-label="Last">
                    <span aria-hidden="true">@this.Model.PageCount</span>
                </a>
            </li>
        }

    </ul>
}

SortFilterPageDemo/SortFilterPageDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SortFilterPageDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SortFilterPageDemo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Students" asp-action="Index">Students</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SortFilterPageDemo - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SortFilterPageDemo/SortFilterPageDemo/Views/Students/Index.cshtml
@model ReflectionIT.Mvc.Paging.PagingList<SortFilterPageDemo.Models.Aluno>


@{
    ViewData["Title"] = "Suppliers";
}

<h2>Suppliers</h2>

@*<nav aria-label="Suppliers navigation example">
    @await this.Component.InvokeAsync("Pager", new { pagingList = this.Model })
</nav>*@

<table class="table">
    <thead>
        <tr>
            <th>
                Nome
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
            </tr>
        }
    </tbody>
</table>

<nav aria-label="anha navigation example">
    <vc:pager paging-list="@Model" />
</nav>